// Todo
export const INIT_TODO = 'INIT_TODO';
export const INIT_TASKS = 'INIT_TASKS';
export const INIT_FINISHED = 'INIT_FINISHED';
export const CHANGE_TASK_NAME = 'CHANGE_TASK_NAME';
export const CHANGE_TASK_DESCRIPTION = 'CHANGE_TASK_DESCRIPTION';
export const CHANGE_TASK_DATE = 'CHANGE_TASK_DATE';
export const CHANGE_TASK_CATEGORY = 'CHANGE_TASK_CATEGORY';
export const CHANGE_TASK_PRIORITY = 'CHANGE_TASK_PRIORITY';
export const CHANGE_TASK_REPEAT = 'CHANGE_TASK_REPEAT';
export const SET_TASK = 'SET_TASK';
export const DEFAULT_TASK = "DEFAULT_TASK";

// Category
export const INIT_CATEGORIES = 'INIT_CATEGORIES';
export const CHANGE_CATEGORY_NAME = "CHANGE_CATEGORY_NAME";
export const SET_CATEGORY = "SET_CATEGORY";
export const DEFAULT_CATEGORY = "DEFAULT_CATEGORY";

// Settings
export const UPDATE_SETTINGS = 'UPDATE_SETTINGS';
