export const NEW_NAME = 'UPDATE_NEW_NAME';
export const NEW_DESCRIPTION = 'UPDATE_NEW_DESCRIPTION';
export const ADD_NEW_TASK = 'ADD_NEW_TASK';
export const REMOVE_TASK = "REMOVE_TASK";
export const UPDATE_MODAL_TASK = "UPDATE_MODAL_TASK";

export const EDIT_NAME = "EDIT_NAME";
export const EDIT_DESCRIPTION = "EDIT_DESCRIPTION";
export const UPDATE_TASK = "UPDATE_TASK";
